version: '3.8'

services:
  streamlit_ocr:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
      - ./data:/data # For temporary files, uploads, and outputs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    # Uncomment the following line if you want to run Streamlit in headless mode
    # command: streamlit run app.py --server.headless true
    command: streamlit run app.py --server.port 8501 --server.address 0.0.0.0
    restart: unless-stopped
